version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 8009:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq/
      - rabbit-logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=iman
      - RABBITMQ_DEFAULT_PASS=iman
    networks:
      - rabbitmq

networks:
  rabbitmq:
    name: rabbitmq

volumes:
  rabbit-data:
    name: rabbit-data
  rabbit-logs:
    name: rabbit-logs
